### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by Extra-lightwill** [Extra-lightwill/sql-demo-fork-rfs#1]
- [ ] implement add Task mutation
- [ ] implement edit Task mutation 
- [ ] implement remove Task mutation 
- [ ] implement query total number of Tasks
- [ ] implement search to retrieve Tasks based on dynamic parameters
- [ ] CRUD multiple (plural) example

**Note:** Use connection + GraphQLList in separate queries to cover both use-cases

**Comment by Extra-lightwill** [comment]
@Neitsch

Current commit:

- AFAIK, db models are mapped correctly with GraphQL models
- db tables are created using sequelize logic in connection.js file
- basic front-end UI is done
- TasksMain page functions have been updated
- Database insert for addTaskMutation is working - need to implement user_id insert
- renderTasks function isn't rendering tasks

**Comment by Neitsch** [comment]
👍 
Will look at it soon, sorry for not getting around to it earlier

**Comment by Extra-lightwill** [comment]
Also worth noting that folder/file structure is not set in stone - if you think there's a better way of organising it, particularly the model definitions and sequelize logic, then I'm open to suggestions :)

**Comment by Extra-lightwill** [comment]
@Neitsch I've been a bit short of time recently so haven't been able to contribute much of late - however, I have been running into a couple of problems which I thought I'd share with you:

1. I'm unsure why the task edge array isn't being populated (and therefore the renderTasks function has nothing to render) 
2. I'm unsure how to best make user_id equivalent to the id of viewer: (see here: https://github.com/Extra-lightwill/sql-demo-fork-rfs/blob/master/server/data/schema.js#L210)

I think if these two issues are solved, I (we) should be able to complete the roadmap fairly quickly.
